[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
tipstack = "AUMYjmiZZ7drVv6VzVo23BFKPwXLBmMQf2w8aQW731r6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
